name: IPTV Merge Advanced
run-name: Auto IPTV Update

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

permissions:
  contents: write

# Prevent queued workflows
concurrency:
  group: iptv-merge
  cancel-in-progress: true

jobs:
  merge:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Create playlist folder
      - name: Create Folder
        run: mkdir -p playlists

      # Download playlists
      - name: Download Playlists
        run: |
          curl --retry 3 --connect-timeout 20 -L "https://raw.githubusercontent.com/srhady/CricketLive/refs/heads/main/playlist.m3u" -o playlists/cricket.m3u

          curl --retry 3 --connect-timeout 20 -L "https://raw.githubusercontent.com/srhady/bingstream/refs/heads/main/playlist.m3u" -o playlists/bing.m3u

          curl --retry 3 --connect-timeout 20 -L "https://raw.githubusercontent.com/srhady/tapmad-bd/refs/heads/main/tapmad_bd.m3u" -o playlists/tapmad.m3u

          curl --retry 3 --connect-timeout 20 -L "https://raw.githubusercontent.com/srhady/SonyLiv/refs/heads/main/sonyliv_playlist.m3u" -o playlists/sonyliv.m3u

          curl --retry 3 --connect-timeout 20 -L "https://raw.githubusercontent.com/srhady/Fancode-bd/refs/heads/main/main_playlist.m3u" -o playlists/fancode.m3u

      # Merge playlists
      - name: Merge Playlists
        run: |
          OUTPUT="combined.m3u"

          echo "#EXTM3U" > $OUTPUT

          # MAIN PLAYLIST FIRST
          curl --retry 3 --connect-timeout 20 -L "https://raw.githubusercontent.com/MRM3UK/New-try/refs/heads/main/MOVIES%20-%20FTP.m3u" \
          | tail -n +2 >> $OUTPUT

          echo "" >> $OUTPUT

          # CRICKET
          tail -n +2 playlists/cricket.m3u >> $OUTPUT
          echo "" >> $OUTPUT

          # BING
          tail -n +2 playlists/bing.m3u >> $OUTPUT
          echo "" >> $OUTPUT

          # TAPMAD
          tail -n +2 playlists/tapmad.m3u >> $OUTPUT
          echo "" >> $OUTPUT

          # SONYLIV
          tail -n +2 playlists/sonyliv.m3u >> $OUTPUT
          echo "" >> $OUTPUT

          # FANCODE
          tail -n +2 playlists/fancode.m3u >> $OUTPUT

      # Remove duplicate lines
      - name: Remove Duplicates
        run: |
          awk '!seen[$0]++' combined.m3u > clean.m3u
          mv clean.m3u combined.m3u

      # Show statistics
      - name: Playlist Statistics
        run: |
          echo "Total Channels:"
          grep -c "#EXTINF" combined.m3u || true

      # Push changes
      - name: Push Playlist
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add combined.m3u playlists/

          git commit -m "Auto updated playlist" || echo "No changes"

          git push
